
name: Auto Step Task
on:
  schedule:
    # UTC时间 = 北京时间 -8小时
    # 北京时间：09:00、09:30、10:00、10:30、11:00、11:30、12:00、12:30、13:00、13:30、14:00、14:30
    - cron: '7 2 * * *'
    - cron: '30 3 * * *'
    - cron: '0 4 * * *'
    - cron: '25 4 * * *'
    - cron: '11 5 * * *'
    - cron: '21 6 * * *'
    - cron: '0 7 * * *'
    - cron: '47 7 * * *'
    - cron: '15 8 * * *'
    - cron: '51 10 * * *'
    - cron: '24 11 * * *'
    - cron: '30 12 * * *'
  workflow_dispatch:

jobs:
  run-job:
    runs-on: ubuntu-latest
    env:
      ACCOUNT_TEL: ${{ secrets.ACCOUNT_TEL }}
      ACCOUNT_PSW: ${{ secrets.ACCOUNT_PSW }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python step_run.py
